CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50),
    name VARCHAR(255),
    address VARCHAR(255),
    phone VARCHAR(255),
    owner_name VARCHAR(255),
    status VARCHAR(255),
    remark VARCHAR(500),
    opening_time TIME,
    closing_time TIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_stores_code UNIQUE (code)
);

ALTER TABLE stores ADD COLUMN IF NOT EXISTS code VARCHAR(50);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS remark VARCHAR(500);

CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    nickname VARCHAR(64),
    avatar_url VARCHAR(255),
    role VARCHAR(20),
    password VARCHAR(255),
    status VARCHAR(20),
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_staff_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    subject_type VARCHAR(16) NOT NULL,
    subject_id BIGINT NOT NULL,
    device_info VARCHAR(255),
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS sms_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(64)
);

CREATE INDEX IF NOT EXISTS idx_staff_store ON staff (store_id);
CREATE INDEX IF NOT EXISTS idx_refresh_subject ON refresh_tokens (subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_sms_phone_purpose ON sms_verification_codes (phone, purpose, created_at);
