CREATE TABLE IF NOT EXISTS operational_state (
    id BIGINT PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    payload TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
